### ISSUE TITLE
why not include bash ?

### ISSUE THREAD

**Issue by sletort** [Docker-Hub-frolvlad/docker-alpine-miniconda3#1]
Hi frol,

Thanks for you image which I used to build a small runner for gitlab-ci.
I just realized that I cannot use conda environment because "source activate" need to be ran from bash. (I'll add bash to my image)

How do you use conda without bash ?
Sébastien

**Comment by frol** [comment]
I do not use virtual environments inside the container, that is I just install everything into the root environment.
